export const fonts = [
    "Arial",
    "Times New Roman",
    "Segoe UI",
    "Tahoma",
    "Calibri",
    "Frutiger",
    "Helvetica",
    "Futura PT",
    "Myriad Pro",
    "Open Sans",
    "Roboto",
    "Verdana",
    "Adobe Arabic",
    "Droid Arabic Naskh",
    "GE SS Unique Light",
    "Simplon Norm Arabic",
    "Neue Helvetica Arabic",
    "Noto Naskh Arabic",
    "Ubuntu Arabic",
    "Waseem",
    "Zuhair",
    "Dubai",
    "Amiri",
    "Bukra",
    "Bahij Nazanin",
    "Kufam",
    "Lalezar",
    "Mirza",
    "Sakkal Majalla",
    "Scheherazade",
    "Tajawal",
    "Lateef",
    "Reem Kufi",
    "Almarai",
    "Cairo",
    "Harmattan",
    "Janna LT",
    "Mada",
    "Muna",
    "JF Flat",
    "JF Hitham",
    "JF Nizar",
    "JF Deco",
    "JF Ziba",
    "JF Unicode Naskh",
    "JF Typist",
    "JF Flat Arabic",
    "JF Nizar Serif",
    "JF Zaytoon",
    "JF Zuhair",
    "JF Deco Arabic",
    "JF Hujjat",
    "JF Noon",
    "JF Raya",
    "JF Riqa",
    "JF Tulisan",
    "JF Adeeb",
    "JF Zarkan",
    "JF Besmellah",
    "JF Noori Nastaleeq",
    "JF Noori Nastaleeq Kasheeda",
    "JF Noori Nastaleeq V1.0",
    "JF Noori Nastaleeq V2.0",
    "JF Noori Nastaleeq V3.0",
    "JF Noori Nastaleeq V4.0",
    "JF Noori Nastaleeq V5.0",
    "JF Noori Nastaleeq V6.0",
    "JF Noori Nastaleeq V7.0",
    "JF Noori Nastaleeq V8.0",
    "JF Noori Nastaleeq V9.0",
    "JF Noori Nastaleeq V10.0",
    "JF Noori Nastaleeq V11.0",
    "JF Noori Nastaleeq V12.0",
    "JF Noori Nastaleeq V13.0",
    "JF Noori Nastaleeq V14.0"
];
