import {
    texture1,
    texture2,
    texture3,
    texture4,
    texture5,
    texture6,
    texture7,
    texture8,
    texture9,
    texture10,
    logo1,
    logo2,
    logo3,
    logo4,
    logo5,
    logo6,
    logo7,
    logo8
} from "../assets";

export const texturesLogos = [
    { name: "Texture 1", image: texture1, type: "texture" },
    { name: "Texture 2", image: texture2, type: "texture" },
    { name: "Texture 3", image: texture3, type: "texture" },
    { name: "Texture 4", image: texture4, type: "texture" },
    { name: "Texture 5", image: texture5, type: "texture" },
    { name: "Texture 6", image: texture6, type: "texture" },
    { name: "Texture 7", image: texture7, type: "texture" },
    { name: "Texture 8", image: texture8, type: "texture" },
    { name: "Texture 9", image: texture9, type: "texture" },
    { name: "Texture 10", image: texture10, type: "texture" },
    { name: "Front Logo 1", image: logo1, type: "frontLogo" },
    { name: "Front Logo 2", image: logo2, type: "frontLogo" },
    { name: "Front Logo 3", image: logo3, type: "frontLogo" },
    { name: "Front Logo 4", image: logo4, type: "frontLogo" },
    { name: "Front Logo 5", image: logo5, type: "frontLogo" },
    { name: "Front Logo 6", image: logo6, type: "frontLogo" },
    { name: "Front Logo 7", image: logo7, type: "frontLogo" },
    { name: "Front Logo 8", image: logo8, type: "frontLogo" },
    { name: "Back Logo 1", image: logo1, type: "backLogo" },
    { name: "Back Logo 2", image: logo2, type: "backLogo" },
    { name: "Back Logo 3", image: logo3, type: "backLogo" },
    { name: "Back Logo 4", image: logo4, type: "backLogo" },
    { name: "Back Logo 5", image: logo5, type: "backLogo" },
    { name: "Back Logo 6", image: logo6, type: "backLogo" },
    { name: "Back Logo 7", image: logo7, type: "backLogo" },
    { name: "Back Logo 8", image: logo8, type: "backLogo" },
];
