import React, { useState } from "react";
import CustomButton from "../CustomButton.jsx";
import { buttonTypes, handleSubmit, imageStyles } from "../../utils/ai-util.js";
import "./AIPicker.css";

const AIPicker = () => {
	const [prompt, setPrompt] = useState("");
	const [style, setStyle] = useState("default");
	const [creativity, setCreativity] = useState(5);
	const [generatingImg, setGeneratingImg] = useState(false);
	const [generatedImage, setGeneratedImage] = useState(null); // State to store the generated image URL

	const handleGenerate = async (type) => {
		if (!prompt) {
			alert("Please enter a prompt!");
			return;
		}

		setGeneratingImg(true);
		setGeneratedImage(null); // Clear previous image

		try {
			const imageUrl = await handleSubmit(type, style, creativity, prompt, setGeneratingImg);
			if (imageUrl) {
				setGeneratedImage(imageUrl); // Set the fetched image URL
			}
		} catch (error) {
			console.error("Error generating image:", error);
			alert("Failed to generate image. Please try again.");
		} finally {
			setGeneratingImg(false);
		}
	};


	return (
		<div className="ai-picker">
			{/* Header Section */}
			<div className="ai-picker-header">
				<h2>AI Assistant</h2>
				<p>Enter your prompt below and let AI help create something amazing!</p>
			</div>

			{/* Prompt Input */}
			<div className="ai-picker-section">
				<label htmlFor="prompt" className="ai-picker-label">
					Your Prompt
				</label>
				<textarea
					id="prompt"
					rows={5}
					value={prompt}
					onChange={(e) => setPrompt(e.target.value)}
					placeholder="Ask AI..."
					className="ai-picker-textarea"
				/>
			</div>

			{/* Style Selector */}
			<div className="ai-picker-section">
				<label htmlFor="style" className="ai-picker-label">
					Choose Style
				</label>
				<select
					id="style"
					value={style}
					onChange={(e) => setStyle(e.target.value)}
					className="ai-picker-select"
				>
					{imageStyles.map(({ value, label }) => (
						<option key={value} value={value}>
							{label}
						</option>
					))}
				</select>
			</div>

			{/* Creativity Slider */}
			<div className="ai-picker-section">
				<label htmlFor="creativity" className="ai-picker-label">
					Creativity Level
				</label>
				<input
					id="creativity"
					type="range"
					min="1"
					max="10"
					value={creativity}
					onChange={(e) => setCreativity(e.target.value)}
					className="ai-picker-slider"
				/>
				<p
					className={`ai-picker-creativity-level ${
						creativity > 7 ? "high" : creativity < 4 ? "low" : "medium"
					}`}
				>
					Level: {creativity}
				</p>
			</div>

			{/* Action Buttons */}
			<div className="ai-picker-actions">
				{generatingImg ? (
					<div className="ai-picker-loader">
						<div className="spinner"></div>
					</div>
				) : (
					buttonTypes.map(({ type, label, buttonStyle }) => (
						<CustomButton
							key={type}
							type={buttonStyle}
							title={label}
							handleClick={() => handleGenerate(type)}
							customStyles="ai-picker-button"
						/>
					))
				)}
			</div>

			{/* Generated Image Section */}
			{generatedImage && (
				<div className="ai-picker-result">
					<h3>Generated Image:</h3>
					<img src={generatedImage} alt="Generated by AI" className="ai-picker-image" />
				</div>
			)}
		</div>
	);
};

export default AIPicker;
