import {FiDownload, FiRefreshCw} from "react-icons/fi";

export const AIResult = ({ image, onRegenerate, onDownload }) => (
    <div className="ai-picker-result">
        <div className="ai-picker-image-wrapper">
            <img src={image} alt="Generated by AI" className="ai-picker-image" />
            <div className="ai-picker-image-icons">
                <button onClick={onRegenerate} aria-label="Regenerate">
                    <FiRefreshCw size={20} />
                </button>
                <button onClick={onDownload} aria-label="Download">
                    <FiDownload size={20} />
                </button>
            </div>
        </div>
    </div>
);
