import { FiDownload, FiRefreshCw } from "react-icons/fi";
import state from '../../store';// Assuming these are globally accessible
import {DecalTypes} from "../../constants/decalTypes.js";

export const AIResult = ({
                             image,
                             onRegenerate,
                             onDownload,
                         }) => {
    const handleDecalClick = (type) => {
        if (!image) {
            alert("No image to apply");
            return;
        }

        const { stateProperty, filterTab } = DecalTypes[type];

        // Update the global state
        state[stateProperty] = image;
    };

    return (
        <div className="ai-picker-result">
            <div className="ai-picker-image-wrapper">
                <img src={image} alt="Generated by AI" className="ai-picker-image" />
                <div className="ai-picker-image-icons">
                    <button onClick={onRegenerate} aria-label="Regenerate">
                        <FiRefreshCw size={20} />
                    </button>
                    <button onClick={onDownload} aria-label="Download">
                        <FiDownload size={20} />
                    </button>
                </div>
            </div>
            <div className="ai-picker-custom-buttons">
                <button
                    onClick={() => handleDecalClick("frontLogo")}
                    className="custom-button"
                >
                    Front
                </button>
                <button
                    onClick={() => handleDecalClick("backLogo")}
                    className="custom-button"
                >
                    Back
                </button>
                <button
                    onClick={() => handleDecalClick("full")}
                    className="custom-button"
                >
                    Texture
                </button>
            </div>
        </div>
    );
};
